name: Tests

on:
    push:
        branches: [master]
    pull_request:

jobs:
    phpunit:
        name: PHPUnit with PHP ${{ matrix.php-version }}
        strategy:
            matrix:
                php-version:
                    - '7.3'
                    - '7.4'
                    - '8.0'
                    - '8.1'
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Install PHP with extensions
                uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    extensions: intl
                    php-version: ${{ matrix.php-version }}

            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
                    restore-keys: |
                        composer-${{ runner.os }}-${{ matrix.php-version }}-

            -   name: Download dependencies
                run: composer update --no-interaction --no-progress --optimize-autoloader

            -   name: Run tests
                run: ./vendor/bin/phpunit
